export const initialDataState = {
  fp: {
    files: {
      ILF: {},
      EIF: {},
      IE: {},
      IQ: {},
      IO: {},
    },
    language: {
      value: 0,
    },
    factors: {
      'Data Connections': {},
      'Distributed data processing': {},
      'Performance requirements': {},
      'Hardware requirements': {},
      'How often transactions are performed': {},
      'What percentage of information is entered online': {},
      'Efficiency for the user': {},
      'How many ILFs are updated online': {},
      'Complex logical or mathematical processing': {},
      'Multi users application': {},
      'The complexity of the installation': {},
      'Efficient or automated start, backup, restore': {},
    },
  },
  cocomo: {
    W1: {},
    W2: {},
    W3: {},
    W4: {},
    W5: {},
    PERS: {},
    RCPX: {},
    RUSE: {},
    PDIF: {},
    PREX: {},
    FCIL: {},
    SCED: {},
  },
  expert: {
    staff: {
      Analytics: {},
      Design: {},
      Programming: {},
      Testing: {},
      Management: {},
      Support: {},
      Commissioning: {},
    },
    expences: {
      VAT: {},
      Income: {},
      'Travel expenses': {},
      'Overhead expenses': {},
      'Deductions to insurance funds': {},
    },
  },
};
